spring:
  banner:
    image:
      location: banner.txt
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    change-log: classpath:config/liquibase-changelog.xml
server:
  port: 8081

jwt:
  secret: OTI2OWU5MzhlMjdmYTE3NDllM2Q0OGUwNDUzZDcyYTY0NmNlMGQwODUxNmViNDYyYTQ4YTYwZjliZWVlYmM5MmE4MWI1OWVkYmY3OTU2YzlhYTFhNjNkODQ4OTNmOGMzNzAyY2MyMmU5YzViM2U1NDFlNjgzZGQyY2U4OWM2ZjM=
